import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>My Website</h1>
          <nav>
            <Link href="/home">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/product">Product</Link>
          </nav>
        </header>
        <main>{children}</main> {/* This renders the page content */}
        <footer>&copy; 2024 My Website</footer>
      </body>
    </html>
  );
}
